---
- name: Tests for verifying the OpenShift installation (Lab-Module 1)
  hosts: localhost
  tasks:
    - name: Check that oc client
      command: oc version

    - name: Get channel for operator from packagemanifest
      command: oc get packagemanifest dynatrace-operator -n openshift-marketplace -o jsonpath='{.status.defaultChannel}'
      register: channel
      
    - name: Get catalog source for operator from packagemanifest
      command: oc get packagemanifest dynatrace-operator -n openshift-marketplace -o jsonpath='{.status.catalogSource}'
      register: catalog_source
      
    - name: use Jinja2 template to configure subscription
       template:
         src: subscription.j2
         dest: subscription.yaml
