---
- name: Public key is deployed to managed hosts for Ansible
  hosts: DevHosts
  vars:
    user: itsbt

  tasks:
    - name: Ensure key is in '{{ user }}' /'s ~/.ssh/authorized_hosts
      with_file:
        - ~/.ssh.id_rsa.pub
      ansible.posix.authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ item }}"
