---
- hosts: nodes
  user: root

  tasks:
    - name: Update Docker Options
      ansible.builtin.replace:
        path: /etc/sysconfig/docker
        regexp: --selinux-enabled
        replace: --selinux-enabled --signature-verification=false
        backup: true

    - name: Restart Docker Service
      ansible.builtin.service:
        name: docker.service
        state: restarted
