---
- name: Automation of LDAP and user manipulation module
  hosts: masters
  become_user: root

  tasks:
    - name: Login as system:admin
      ansible.builtin.command: oc login -u system:admin

    - name: Sync all of the LDAP groups
      ansible.builtin.command: oc adm groups sync --sync-config=/opt/lab/support/groupsync.yaml --confirm

    - name: Check for app-dev project
      register: project_out
      ignore_errors: true
      ansible.builtin.command: oc get project app-dev

    - name: Create app-dev project
      when: project_out | failed
      ansible.builtin.command: oc adm new-project app-dev --display-name="Application Development"

    - name: Check for app-test project
      register: project_out
      ignore_errors: true
      ansible.builtin.command: oc get project app-test

    - name: Create app-dev project
      when: project_out | failed
      ansible.builtin.command: oc adm new-project app-test --display-name="Application Test"

    - name: Check for app-prod project
      register: project_out
      ignore_errors: true
      ansible.builtin.command: oc get project app-prod

    - name: Create app-prod project
      when: project_out | failed
      ansible.builtin.command: oc adm new-project app-prod --display-name="Application Production"

    - name: Give cluster-reader to fancy-dev
      ansible.builtin.command: oc adm policy add-cluster-role-to-group cluster-reader ose-fancy-dev

    - name: Manipulate group roles
      with_items:
