---
- name: Verification tests for lab module 4.3
  hosts: masters
  tasks:
    - name: Login as system:admin so as to list all groups and projects
      ansible.builtin.command: oc login -u system:admin

    - name: Look for all of the synced groups
      with_items:

    - name: Check for ose-user group users
      register: ose_user_users
      failed_when: >
      ansible.builtin.command: oc get -o jsonpath='{.users}' group ose-user

    - name: check for ose-normal-dev group users
      register: normaldev_users
      failed_when: >
      ansible.builtin.command: oc get -o jsonpath='{.users}' group 'ose-normal-dev'

    - name: Check for ose-fancy-dev group users
      register: fancydev_users
      failed_when: >
      ansible.builtin.command: oc get -o jsonpath='{.users}' group ose-fancy-dev

    - name: Check for ose-teamed-app group users
      register: teamedapp_users
      failed_when: >
      ansible.builtin.command: oc get -o jsonpath='{.users}' group ose-teamed-app

    - name: Login as normaluser1
      ansible.builtin.command: oc login -u normaluser1 -p openshift

    - name: Check that normaluser1 cannot see projects
      register: project_out
      failed_when: project_out | success
      ansible.builtin.command: oc get project app-dev

    - name: Login as fancyuser1
      ansible.builtin.command: oc login -u fancyuser1 -p openshift

    - name: cluster-reader (fancyuser1) should be able to see default project
      ansible.builtin.command: oc get project default

    - name: Login as teamuser1
      ansible.builtin.command: oc login -u teamuser1 -p openshift

    - name: teamuser1 should see prod project
      ansible.builtin.command: oc get project app-prod

    - name: Switch to prod project
      ansible.builtin.command: oc project app-prod

    - name: teamuser1 cannot create in app-prod
      register: result
      failed_when: result | success
      ansible.builtin.command: oc new-app docker.io/siamaksade/mapit

    - name: Login as cluster administrator
      ansible.builtin.command: oc login -u system:admin

    - name: Delete projects
      with_items:
        - app-dev
        - app-test
        - app-prod
      ansible.builtin.command: oc delete project {{ item }}
