---
- name: Update SSL Certs for hosts of Satellite 6.5
  hosts: prod
  become: yes
  become_user: root
  vars:
    bradySecret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ************
    ansible_become_pass: '{{ bradySecret }}'
    server: SatServer.motel6.com
    katello_ca: katello-ca-consumer-latest.noarch.rpm
  tasks:
    - name: 'Download {{ katello_ca }} from {{ server }}'
      get_url:
        url: 'https://{{ server }}/pub/{{ katello_ca }}'
        dest: /tmp/
        validate_certs: no
    - name: Remove Old Satellite Cert
      yum:
        name: 'katello-ca-consumer*'
        state: absent
    - name: Install '{{ katello_ca }}'
      yum:
        name: '/tmp/{{ katello_ca }}'
        state: present
      ignore_errors: yes
    - name: Create puppet cert
      puppet:
      ignore_errors: yes
      register: puppet_output
    - name: Print puppet output
      debug:
        msg: '{{ puppet_output }}'
    - name: Register insights
      command: insights-client --status
      register: insights_output
    - name: Print insights output
      debug:
        msg: '{{ insights_output }}'
