---
- name: Register Host to Satellite 6.5
  hosts: localhost
  become: yes
  
  vars:
    server: server.domain.com
    pkg:
      katello_ca: katello-ca-consumer-latest.noarch.rpm
      katello: katello_agent
      insights: insights-client
      puppet: puppet
    org_id: 1
    activationkey: rhel7_standard_prod
  
  tasks:
    - name: Download '{{ pkg.katello_ca }}' from '{{ server }}'
      get_url:
        url: 'https://{{ server }}/pub/{{ pkg.katello_ca }}'
        dest: '/tmp/{{ pkg.katello_ca }}'
        validate_certs: no
    - name: Install '{{ pkg.katello_ca }}'
      yum:
        name: '/tmp/{{ pkg.katello_ca }}'
        state: present
    - name: Register to '{{ server }}'
      redhat_subscription:
        state: present
        org_id: '{{ org_id }}'
        activationkey: '{{ activationkey }}'
