---
- name: Verifying project request template
  hosts: masters
  tasks:
    - name: Login as system:admin to create projects
      ansible.builtin.command: oc login -u system:admin

    - name: Check for template-test project
      register: template_out
      ignore_errors: true
      ansible.builtin.command: oc get project template-test

    - name: Checking the creation of a new project
      when: template_out | failed
      ansible.builtin.command: oc new-project template-test

    - name: Checking if quota is present for this project
      ansible.builtin.command: oc get quota template-test-quota -n template-test

    - name: Checking if limitrange is present for the created project
      ansible.builtin.command: oc get limits template-test-limits -n template-test

    - name: Delete template-test project
      ansible.builtin.command: oc delete project template-test
