---

- hosts: masters

  tasks:
    - name: Running the Ansible Playbook to kickstart the OCP installation
      command: ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
...
